name: Build with Codemagic

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger Codemagic build
      uses: codemagic/trigger-workflow@v1
      with:
        app_id: ${{ secrets.CODEMAGIC_APP_ID }}
        workflow_id: ${{ secrets.CODEMAGIC_WORKFLOW_ID }}
        branch: ${{ github.ref_name }}
        environment_variables: |
          CM_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          CM_PULL_REQUEST_NUMBER="${{ github.event.number }}" 